# Generated by Django 4.2.28 on 2026-02-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
