# Generated by Django 4.2.28 on 2026-02-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='year',
            field=models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')], default=1),
            preserve_default=False,
        ),
    ]
