# Generated by Django 4.2.28 on 2026-02-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_post_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(upload_to='resources/'),
        ),
    ]
