# Generated by Django 4.2.28 on 2026-02-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_alter_resource_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='file',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='resource',
            name='file_name',
            field=models.CharField(default='default.pdf', max_length=200),
            preserve_default=False,
        ),
    ]
